[graph]
all-features        = false
no-default-features = false
targets             = []

[output]
feature-depth = 1

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
crate         = "ring"
expression    = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore     = true
registries = []
